"""initial_schema

Revision ID: 8952b948d5be
Revises: 
Create Date: 2026-04-19 15:48:15.025024+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8952b948d5be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kvk_number', sa.String(length=32), nullable=True),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('type', sa.Enum('installateur', 'klant', 'admin', name='organisation_type'), nullable=False),
    sa.Column('subscription_plan', sa.String(length=64), nullable=True),
    sa.Column('subscription_status', sa.String(length=64), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regelingen_config',
    sa.Column('code', sa.Enum('ISDE', 'EIA', 'MIA', 'VAMIL', 'DUMAVA', name='regeling_code'), nullable=False),
    sa.Column('naam', sa.String(length=128), nullable=False),
    sa.Column('beschrijving', sa.Text(), server_default='', nullable=False),
    sa.Column('actief', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_investering', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('max_subsidie', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aanvraag_termijn_dagen', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regelingen_config_code'), 'regelingen_config', ['code'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'installateur', 'klant', name='user_role'), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('last_name', sa.String(length=128), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organisation_id'), 'users', ['organisation_id'], unique=False)
    op.create_table('subsidie_aanvragen',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('aanvrager_id', sa.UUID(), nullable=False),
    sa.Column('installateur_id', sa.UUID(), nullable=True),
    sa.Column('regeling', sa.Enum('ISDE', 'EIA', 'MIA', 'VAMIL', 'DUMAVA', name='regeling_code'), nullable=False),
    sa.Column('type_aanvrager', sa.Enum('particulier', 'zakelijk', 'vve', 'maatschappelijk', 'ondernemer', name='type_aanvrager'), nullable=False),
    sa.Column('status', sa.Enum('intake', 'documenten', 'review', 'ingediend', 'goedgekeurd', 'afgewezen', name='aanvraag_status'), server_default='intake', nullable=False),
    sa.Column('maatregel', sa.Enum('warmtepomp', 'isolatie', 'energiesysteem', 'meerdere', name='maatregel'), nullable=False),
    sa.Column('investering_bedrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('geschatte_subsidie', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('toegekende_subsidie', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aaa_lex_fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aaa_lex_fee_bedrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('deadline_datum', sa.Date(), nullable=True),
    sa.Column('deadline_type', sa.Enum('EIA_3maanden', 'DUMAVA_2jaar', 'DUMAVA_3jaar', name='deadline_type'), nullable=True),
    sa.Column('rvo_aanvraagnummer', sa.String(length=128), nullable=True),
    sa.Column('rvo_status', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aanvrager_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installateur_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subsidie_aanvragen_aanvrager_id'), 'subsidie_aanvragen', ['aanvrager_id'], unique=False)
    op.create_index(op.f('ix_subsidie_aanvragen_installateur_id'), 'subsidie_aanvragen', ['installateur_id'], unique=False)
    op.create_index(op.f('ix_subsidie_aanvragen_organisation_id'), 'subsidie_aanvragen', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_subsidie_aanvragen_regeling'), 'subsidie_aanvragen', ['regeling'], unique=False)
    op.create_index(op.f('ix_subsidie_aanvragen_status'), 'subsidie_aanvragen', ['status'], unique=False)
    op.create_table('aanvraag_documenten',
    sa.Column('aanvraag_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.Enum('offerte', 'factuur', 'betalingsbewijs', 'foto_installatie', 'werkbon', 'energielabel', 'kvk_uittreksel', 'technische_specs', 'energielijst_bewijs', 'milieulijst_bewijs', 'maatwerkadvies', 'begroting', 'foto_voor', 'foto_na', name='document_type'), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('storage_url', sa.String(length=1024), nullable=False),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['aanvraag_id'], ['subsidie_aanvragen.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aanvraag_documenten_aanvraag_id'), 'aanvraag_documenten', ['aanvraag_id'], unique=False)
    op.create_table('installateur_leads',
    sa.Column('installateur_id', sa.UUID(), nullable=False),
    sa.Column('aanvraag_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('nieuw', 'contact_opgenomen', 'gewonnen', 'verloren', name='lead_status'), server_default='nieuw', nullable=False),
    sa.Column('regio', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aanvraag_id'], ['subsidie_aanvragen.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['installateur_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installateur_leads_aanvraag_id'), 'installateur_leads', ['aanvraag_id'], unique=False)
    op.create_index(op.f('ix_installateur_leads_installateur_id'), 'installateur_leads', ['installateur_id'], unique=False)
    op.create_index(op.f('ix_installateur_leads_regio'), 'installateur_leads', ['regio'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installateur_leads_regio'), table_name='installateur_leads')
    op.drop_index(op.f('ix_installateur_leads_installateur_id'), table_name='installateur_leads')
    op.drop_index(op.f('ix_installateur_leads_aanvraag_id'), table_name='installateur_leads')
    op.drop_table('installateur_leads')
    op.drop_index(op.f('ix_aanvraag_documenten_aanvraag_id'), table_name='aanvraag_documenten')
    op.drop_table('aanvraag_documenten')
    op.drop_index(op.f('ix_subsidie_aanvragen_status'), table_name='subsidie_aanvragen')
    op.drop_index(op.f('ix_subsidie_aanvragen_regeling'), table_name='subsidie_aanvragen')
    op.drop_index(op.f('ix_subsidie_aanvragen_organisation_id'), table_name='subsidie_aanvragen')
    op.drop_index(op.f('ix_subsidie_aanvragen_installateur_id'), table_name='subsidie_aanvragen')
    op.drop_index(op.f('ix_subsidie_aanvragen_aanvrager_id'), table_name='subsidie_aanvragen')
    op.drop_table('subsidie_aanvragen')
    op.drop_index(op.f('ix_users_organisation_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_regelingen_config_code'), table_name='regelingen_config')
    op.drop_table('regelingen_config')
    op.drop_table('organisations')

    # Drop ENUM types (not auto-generated by alembic for postgres)
    for enum_name in (
        'lead_status',
        'document_type',
        'deadline_type',
        'maatregel',
        'aanvraag_status',
        'type_aanvrager',
        'regeling_code',
        'user_role',
        'organisation_type',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
    # ### end Alembic commands ###
