"""aaa_lex_projecten

Revision ID: 48c28c869837
Revises: a8102ec2b1ac
Create Date: 2026-04-19 15:56:49.603513+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '48c28c869837'
down_revision: Union[str, None] = 'a8102ec2b1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aaa_lex_projecten',
    sa.Column('external_reference', sa.String(length=128), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('aanvraag_id', sa.UUID(), nullable=True),
    sa.Column('pandadres', sa.String(length=512), nullable=False),
    sa.Column('postcode', sa.String(length=16), nullable=False),
    sa.Column('plaats', sa.String(length=128), nullable=False),
    sa.Column('bouwjaar', sa.Integer(), nullable=True),
    sa.Column('huidig_energielabel', sa.String(length=4), nullable=True),
    sa.Column('nieuw_energielabel', sa.String(length=4), nullable=True),
    sa.Column('type_pand', sa.String(length=64), nullable=True),
    sa.Column('oppervlakte_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dakoppervlakte_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('geveloppervlakte_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('aanbevolen_maatregelen', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('geschatte_investering', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('geschatte_co2_besparing', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ingevoerd_door', sa.String(length=128), nullable=True),
    sa.Column('notities', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['aanvraag_id'], ['subsidie_aanvragen.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aaa_lex_projecten_aanvraag_id'), 'aaa_lex_projecten', ['aanvraag_id'], unique=False)
    op.create_index(op.f('ix_aaa_lex_projecten_external_reference'), 'aaa_lex_projecten', ['external_reference'], unique=False)
    op.create_index(op.f('ix_aaa_lex_projecten_organisation_id'), 'aaa_lex_projecten', ['organisation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aaa_lex_projecten_organisation_id'), table_name='aaa_lex_projecten')
    op.drop_index(op.f('ix_aaa_lex_projecten_external_reference'), table_name='aaa_lex_projecten')
    op.drop_index(op.f('ix_aaa_lex_projecten_aanvraag_id'), table_name='aaa_lex_projecten')
    op.drop_table('aaa_lex_projecten')
    # ### end Alembic commands ###
